name: Coverage

on:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Coverage

    steps:
      - name: ✨ Checkout repository
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: 🐘 Set up Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1

      - name: 🧪 Run tests
        run: ./gradlew check

      - name: 🎯️ Upload to Codecov
        uses: codecov/codecov-action@v3
